### ISSUE TITLE
MONGO_DB_NAME contains mongo_db_uri options

### ISSUE THREAD

**Issue by lloubiere** [hadrien/pyramid_mongokit#1]
mongo db uri may contain options (http://docs.mongodb.org/manual/reference/connection-string/) and these options are included in MONGO_DB_NAME

example;
MONGO_URI = mongodb://localhost/my_glorious_db?replicaSet=rs_local_a

will give MONGO_DB_NAME = my_glorious_db?replicaSet=rs_local_a

**Comment by merwok** [comment]
Is this still an issue with the current version?

**Comment by hadrien** [comment]
No. For uri: `mongodb://localhost/my_glorious_db?replicaSet=rs_local_a`, you provide:
- `MONGO_URI=mongodb://localhost/?replicaSet=rs_local_a`
- `MONGO_DB_NAME=my_glorious_db`

**Comment by merwok** [comment]
See #4 for a new variant of this issue :)
