### ISSUE TITLE
Define Configurator methods for create_indexes and register_document 

### ISSUE THREAD

**Issue by merwok** [hadrien/pyramid_mongokit#9]
Currently we can use `config.include('pyramid_mongokit')` to set up the connection object and `request.mongo_db` to access the database, but we have to import functions in order to create indices and register document classes at startup time.  It would be nice to have methods on the config object instead.

**Comment by hadrien** [comment]
We added [config.register_document](https://github.com/hadrien/pyramid_mongokit/blob/master/example/__init__.py#L53) and [config.generate_index](https://github.com/hadrien/pyramid_mongokit/blob/master/example/__init__.py#L55)
